name: Python application

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  create:
    tags:
      - v*

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

    - name: Test with pytest
      run: |
        pytest -v -m "not aseprite"

    - name: PyInstaller Windows
      uses: JackMcKew/pyinstaller-action-windows@v0.1.2
      if: startsWith(github.ref, 'refs/tags/')
      with:
          path: .
    
    - name: Release
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        files: "dist/**"

    - uses: actions/upload-artifact@v2
      if: startsWith(github.ref, 'refs/tags/')
      with:
        name: dist/rivals_workshop_assistant.exe
        path: src/dist/windows

    - name: VSCode Dispatch
      uses: peter-evans/repository-dispatch@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
        token: ${{ secrets.REPO_ACCESS_TOKEN }}
        repository: Rivals-Workshop-Community-Projects/rivals-workshop-assistant-vscode
        event-type: exe-push

    - name: GMEdit Dispatch
      uses: peter-evans/repository-dispatch@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
        token: ${{ secrets.REPO_ACCESS_TOKEN }}
        repository: Rivals-Workshop-Community-Projects/rivals-workshop-assistant-gmedit
        event-type: exe-push
